version: "3"
services:
  # Laravel(PHP7.2)
  laravel:
    build: ./laravel
    ports:
      - 8000:8000
    volumes:
      - ./laravel/html:/var/www/html
    working_dir: "/var/www/html"
    tty: true
    depends_on:
      - mysql

  # Vue.js
  vue:
    build: ./vue
    ports:
      - 80:80
    volumes:
      - ./vue/html:/html
    working_dir: "/html"
    tty: true

  # MySQL
  mysql:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_DATABASE: sample_db
    volumes:
      - mysql-data:/var/lib/mysql

# named volumeでデータを永続化
volumes:
  mysql-data:
