version: "3"
services:
  # Laravel(PHP7.2)
  laravel:
    build: ./laravel
    ports:
      - 8000:8000
    volumes:
      - ./laravel/html:/var/www/html
    working_dir: "/var/www/html"
    tty: true

  # Vue.js
  vue:
    build: ./vue
    ports:
      - 80:80
    volumes:
      - ./vue/html:/html
    working_dir: "/html"
    tty: true
